# Generated by Django 2.2.10 on 2020-04-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='collaboration_requests',
            field=models.ManyToManyField(blank=True, to='core.CollaborationRequest'),
        ),
        migrations.AddField(
            model_name='competence',
            name='collaborations',
            field=models.ManyToManyField(blank=True, to='core.Collaboration'),
        ),
    ]
