# Generated by Django 2.2.10 on 2020-04-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200419_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='collaboration_requests',
            field=models.ManyToManyField(blank=True, related_name='competences', to='core.CollaborationRequest'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='collaborations',
            field=models.ManyToManyField(blank=True, related_name='competences', to='core.Collaboration'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='competences', to='core.Student'),
        ),
    ]
