# Generated by Django 2.2.10 on 2020-05-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200428_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboration',
            name='status',
            field=models.CharField(blank=True, choices=[('IP', 'In progress'), ('CA', 'Cancelled'), ('PF', 'Pending final'), ('FI', 'Finished')], default='IP', max_length=2),
        ),
    ]
