# Generated by Django 2.2.10 on 2020-05-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200501_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboration',
            name='publication_date',
        ),
    ]
