# Generated by Django 2.2.10 on 2020-04-15 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='collaboration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Collaboration'),
        ),
        migrations.AddField(
            model_name='message',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student'),
        ),
    ]
