# Generated by Django 2.2.10 on 2020-05-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200424_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='collaboration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.Collaboration'),
        ),
    ]
